propagate_decorations = True
use_partial_tag_matches_positive = True  # TODO: disable this eventually, or somehow avoid problem of adding items with partial tags
use_partial_tag_matches_negative = False
use_partial_text_matches_positive = True
use_partial_text_matches_negative = False
db_path = 'metalist.2.0.db'  # TODO from root or somewhere else
max_results = 50  # TODO need dynamic pagination
always_add_to_global_top = True
outdent_all_siblings_below = True
inherit_text = True
